---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dockerhub-pull-secret
  namespace: {{ .Release.Namespace | quote }}
spec:
  encryptedData:
    .dockerconfigjson: AgBlR0vB9zcD68wuNZlsDryKsP5ySD3kG6EMx9e0VHpz4LYU9Q3GyA6yaEkjxHdazwCJPprZxYNyL/IraIuSua+YyA9p2f8QtRhS9yva7ARHcet4kbP4Ev/jkEQfy+4x/OrORUtSkJNZCgq0WtuEpv06gM2/R6tqEgoMgBA9LsNrWhBMEIwUyz35oRQUcrpW+FBL9LEVwruqZ7VBEc55ZUfXiICtoY0q3SrQ9P57xVGz4FG7D99wIARJl7QIfMAzUIvLNTWBSFw/XLUu2d+f4EKy3bPJ1vSHEy3Q6lurxinklXLnUdRsm9ijCOzLgDz+l0oU72q2Xa67PzHqw1fscCHhFFp2XhJjWsmGUPC8t/mROzQfkHaT0jYpbhkayFKn+wtXfxV0jC9YJ+JckUkg4LdTTARcQ7/+oFYOLP+51xnCaokcaFNQJJ8HC6QIrVfIku9eGgDa95on+5i3SP+HPj1WzXckqJUuTYKak0wk/NsmpxwWsCuJt83TgoPzxsJ5o/AASthSqGt5QNEc5R8QL2wRtaYt+80CPqa+8QzqdyGF8kNVw4wG8ZGe5E59WCBg2FkBhNfFjkwg+OTSEIr1MV5i5qnUGgKDHGGtRk/8TJ7KOrbYQhO95y9d2lIjhgMHrnpK3tvomDn3jQTY0e7XiYPUnWvQsmkTCAw9Kyr1oatPp3q/V4XftbPl4Sozo7+mUeard9JIxPwBhmRIJfAYO8knyv0YAR96R/wh5mcMA5k+JFaHdSceNeGisJ43P/9VvVhr/VP1XpwlnmwDex6nRP+g2eP5n+daXELFV2jEwbzFgd4gSjeNiZDVXJdJpdZzFDOzO/EOv1l9wQRe4WnUJrQLIavB2ciCq0/SReXqFdDzF9J5DkdQT+1ETHM37XTngrZdKMuObeJibe4oAfOjmuoJiM9fjSz50k5jGTiWzHTVH2Tosip1752ZAA==
  template:
    metadata:
      name: dockerhub-pull-secret
      namespace: {{ .Release.Namespace | quote }}
    type: kubernetes.io/dockerconfigjson
