---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dockerhub-pull-secret
  namespace: {{ .Release.Namespace | quote }}
spec:
  encryptedData:
    .dockerconfigjson: AgCYZw+NzgOKc85myIKMEZSc2ePQyoNWy7JVdkZxVwdVVlzXrqGhjOgN3gG/eMG3p1L7HmlvuP7dQhGuYl/nSYFPu/riQjZV92IxX1Rl9SNJDMLS/tabriDzVVnLHTJ5ZxvsKuhPOhHO6KpTzgrpqC9u1RgiE/D6xPCdfQz5YiP+mtpSb7oaQn7Dh/YFWUggK+V+mNcSFQT3JZ4d6ZVztCHaeVfwRiYgbdJO0BsBt+4Kkste0A/JuC+7fcNGVjRSpqm0s0N5ODIqYAXMXOfwX1h1dEovxSpzpwgGNnD8Osj056V+27Eco19jlrn/DFqRO/z2m8q0568wk2RkCEofiavqBORjfosaUvGLC6ApdIc/tlK4Lv3nTE5v3y1PrcKnYEiSTPx5OVJNHgDe9Q95zxu5Ep+0qVuJVMdJVvz4wEL2GOZvF95QrpBSuF5eQSqXFt1/7TEHkyswO3olSJNzhhxZlnJpx1UKTcKlKKYyWOmGQd8eqA8RyJB4tLNZQxKdUdOo9T9T8fWGGdOHgnOea2vgKeSNg9xCTk0H9YlcxQK1x/QVTCfLzC//n/qkrAo4N4lFw8gcVRKLkofNEZSt47YLvYaQnmd3eIoMgas4ytJUXVHLXwqcOc/XiqlrUPglTMFKeENSlBh4R5nocjQ2WwYUXpc5OtZPIL/ZvGwX9ODEfS6KOrL6TPAGlWfCog0l68WmUUfuFnBPtuNfcIkOJb1wvLbMn4sM1JDpimCF9sc6VBKlznoel9nOu8AX+/9nxAPFTVFJDkg+K4mSRcJtPKg7qyO9Eis2ybVBoDabwaMNTsZx6eulu8LIjBiTIjbuYYx5tayGecIMg0kqQDqIljBHKYHtJyqtlMAOVbV+q2MXwFl0+p9VuiYUhWGflGzZHf7dZ0jGaMZhXjhKR0xbx6LOAVb4RUIzT1+D/19+TKUGUL9kXY8QXngFpQ==
  template:
    metadata:
      name: dockerhub-pull-secret
      namespace: {{ .Release.Namespace | quote }}
    type: kubernetes.io/dockerconfigjson
