---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dockerhub-pull-secret
  namespace: {{ .Release.Namespace | quote }}
spec:
  encryptedData:
    .dockerconfigjson: AgChTd9uMsowr5zPSAD7ciNGguyGE5prylnn+W5PCLxt1X+eYBQA1jhwqQWi0FN2kR7B6hIyl3+TB9D51pHmdq61T/0k5FJY3IvD00GfoVm4EboPljRKcEZm4eDKEvHGJejDutWyD9bytR0AmtGBW3hYoVJ6JNtkdxiMXRAPMzq6f1lEJkPIbYuxRUDljnPwQS/0/zhWfGjgTM0qqYA3iTSYJ3lMBX8g/l4F3Bo4vaOP1PnjKG0bU5fEKu8Mtt56UK34DitltTItpTfNJiuqnIIY4P5OJzySbQ+CK4S1wIx1r95XDMC2TG3Lh6ZA7vf9mGgDNxRceJKzJO56DEfbkWneuVpVtKLWG+lX868ZyidaL350zvFHwPikZsh2X9oF6JbhOZkDqN+DjQUgUmzeyYNAazwA0I+csStzi51I0cNTuLfL88ASD+443BbHyc2FeQFrJ8UyMvhP4bjQZzzl+8kX6dq6/tXDLnWfZY7HbOk0dd9EGXAuoSsHA3vYxrzGcQs9ijqfsaSyZZhAt6evJ9PKOJK6tlEWts6zlIVVb1opJtZ33I+pmywPoa2070tWOXU44X0ZCpsJA4cSFnoGzCpW+mYtDKzrEyyGJ1gp93Z/0A/D5nI8Q6YntuD0fKuNrW71ytwaFjpULrjgo7gTs94nJMmY7aCqA124AKsK5dNCNJkFky2dP7hQPIzopkYC6dlXEVglKzEgsh0vIAmWXMlN7C5aqCpJ4cmoARhyvAuzrkMgn6mWGgi1GBmDnATC4PNmc0YQnEPNhM5oAB6PXIrd+PscY/P0421qWhckag873BO3/5yX+3rSxi+Mu1LFqowo4kxLIoHPVK/s5JFlFce8s+0WeuA9YyvT/t2cHGKFktdlNut5pfkMJO0TpHb74W8Ve2WtNiEh73DUS1mXl00kGz1ow/yevbiT+XqyRxrSrH6ItaC5AXWt6A==
  template:
    metadata:
      name: dockerhub-pull-secret
      namespace: {{ .Release.Namespace | quote }}
    type: kubernetes.io/dockerconfigjson
